[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PUPPETEER_CACHE_DIR = "/opt/buildhome/.cache/puppeteer"
  PUPPETEER_SKIP_DOWNLOAD = "false"

[functions]
  directory = "netlify/functions"

[dev]
  targetPort = 5173
  port = 8888
